import type { NativeToolRoundTrace } from "../native-tool-messages";
import type { RoleToolExecutionResult } from "../tool-use";
import {
  readLegacyBrowserRecoverySummariesFromToolTrace,
  readLegacyApprovalWaitTimeoutRuntimeEvidence,
  readLegacyCompletedSessionEvidenceText,
  readLegacySourceBoundedEvidenceText,
  readLegacyIndependentEvidenceStreamCount,
  readLegacyIndependentEvidenceStreamsContinuation,
  readLegacyTimedOutApprovedBrowserSessionContinuation,
  readLegacyTimedOutSiblingSessionContinuation,
  readLegacyForceApprovalWaitTimeoutLocalCloseoutAfterFailedRepair,
  readLegacyApprovalWaitTimeoutCloseoutRepair,
  readLegacyFalseEvidenceBlockedSynthesisRepair,
  readLegacyFinalRecoveryBudgetCloseoutRepair,
  readLegacyIncompleteApprovedBrowserActionRepair,
  readLegacyMissingApprovalGateRepair,
  readLegacyMissingBrowserEvidenceRepair,
  readLegacyMissingBrowserEvidenceDimensionsRepair,
  readLegacyMissingProductSignalBrowserEvidenceRepair,
  readLegacyMissingRequestedNextActionRepair,
  readLegacyPendingApprovalWaitTimeoutCheckRepair,
  readLegacyPrematurePendingApprovalFinalRepair,
  readLegacySourceEvidenceCarryForwardRepair,
  readLegacyStaleDeniedApprovalRepair,
  readLegacyStalePendingApprovalRepair,
  readLegacyTimeoutFollowupFinalGuidanceRepair,
  readLegacyWeakEvidenceSynthesisRepair,
  readLegacyReadOnlyPermissionQuerySuppression,
} from "../tool-loop-shared";

export const readReadOnlyPermissionQuerySuppression =
  readLegacyReadOnlyPermissionQuerySuppression;
export const readApprovalWaitTimeoutRuntimeEvidence =
  readLegacyApprovalWaitTimeoutRuntimeEvidence;
export const readFinalRecoveryBudgetCloseoutRepair =
  readLegacyFinalRecoveryBudgetCloseoutRepair;
export const readCompletedSessionEvidenceText =
  readLegacyCompletedSessionEvidenceText;
export const readMissingBrowserEvidenceDimensionsRepair =
  readLegacyMissingBrowserEvidenceDimensionsRepair;
export const readMissingBrowserEvidenceRepair =
  readLegacyMissingBrowserEvidenceRepair;
export const readMissingProductSignalBrowserEvidenceRepair =
  readLegacyMissingProductSignalBrowserEvidenceRepair;
export const readMissingApprovalGateRepair = readLegacyMissingApprovalGateRepair;
export const readPendingApprovalWaitTimeoutCheckRepair =
  readLegacyPendingApprovalWaitTimeoutCheckRepair;
export const readPrematurePendingApprovalFinalRepair =
  readLegacyPrematurePendingApprovalFinalRepair;
export const readStalePendingApprovalRepair = readLegacyStalePendingApprovalRepair;
export const readStaleDeniedApprovalRepair = readLegacyStaleDeniedApprovalRepair;
export const readApprovalWaitTimeoutCloseoutRepair =
  readLegacyApprovalWaitTimeoutCloseoutRepair;
export const readForceApprovalWaitTimeoutLocalCloseoutAfterFailedRepair =
  readLegacyForceApprovalWaitTimeoutLocalCloseoutAfterFailedRepair;
export const readIncompleteApprovedBrowserActionRepair =
  readLegacyIncompleteApprovedBrowserActionRepair;
export const readSourceBoundedEvidenceText = readLegacySourceBoundedEvidenceText;
export const readSourceEvidenceCarryForwardRepair =
  readLegacySourceEvidenceCarryForwardRepair;
export const readWeakEvidenceSynthesisRepair = readLegacyWeakEvidenceSynthesisRepair;
export const readTimedOutApprovedBrowserSessionContinuation =
  readLegacyTimedOutApprovedBrowserSessionContinuation;
export const readTimedOutSiblingSessionContinuation =
  readLegacyTimedOutSiblingSessionContinuation;
export const readIndependentEvidenceStreamsContinuation =
  readLegacyIndependentEvidenceStreamsContinuation;
export const readIndependentEvidenceStreamCount =
  readLegacyIndependentEvidenceStreamCount;
export const readBrowserRecoverySummariesFromTrace =
  readLegacyBrowserRecoverySummariesFromToolTrace;
export const readTimeoutFollowupFinalGuidanceRepair =
  readLegacyTimeoutFollowupFinalGuidanceRepair;
export const readMissingRequestedNextActionRepair =
  readLegacyMissingRequestedNextActionRepair;
export const readFalseEvidenceBlockedSynthesisRepair =
  readLegacyFalseEvidenceBlockedSynthesisRepair;

export type InlinePolicyNativeTrace = NativeToolRoundTrace;
export type InlinePolicyToolResult = RoleToolExecutionResult;
